config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  root "books#index"
  resources :articles
  resources :books

  get 'video-gallary' => "books#yt_videos"
  get  'fav_videos', to: 'videos#show_all_fav_videos'
  
  resources :videos do 
    member do 
      post :add_to_favourite
      post :remove_from_favourite
    end
  end
end

app/models/video.rb
class Video < ApplicationRecord
  has_many :user_favourite_videos       
  has_many :users, through: :user_favourite_videos
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: %i[ show edit update destroy add_to_favourite remove_from_favourite]
  before_action :authenticate_user!, only: [:add_to_favourite, :remove_from_favourite, :show_all_fav_videos]

  # GET /videos or /videos.json
  def index
    @videos = Video.all
    if user_signed_in?
      @user_fav_video_ids = (fav_video_ids)
    end
  end

  def show_all_fav_videos
    @videos = Video.all
    @user_fav_videos = (fav_video_ids)
  end

  # GET /videos/1 or /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos or /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: "Video was successfully created." }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1 or /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: "Video was successfully updated." }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1 or /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: "Video was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def add_to_favourite
    UserFavouriteVideo.create(user_id: current_user.id, video_id: @video.id)
    respond_to do |format|
      format.html { redirect_to videos_url, notice: "Video was successfully added to your favourite list." }
    end  
  end

  def remove_from_favourite
    UserFavouriteVideo.find_by(user_id: current_user.id, video_id: @video.id).destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: "Video was successfully removed from your favourite list." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:title, :yt_url, :description)
    end

    def fav_video_ids
      current_user.user_favourite_videos.pluck(:video_id)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_with(model: video) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
        <% video.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :yt_url %>
    <%= form.text_field :yt_url %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<%= link_to 'Log out', destroy_user_session_path, method: :delete %>
<%= link_to 'See the Fav. list', fav_videos_path, class: 'btn btn-success btn-lg ml-1 mt-1' %>
<hr>
<div class="container">
  <div class="row">
    <div class="col-12 col-md-11 mx-md-auto col-lg-9 mx-lg-auto">
      <% @videos.each do |video| %>
        <div class="card shadow rounded-0 mt-3">
          <div class="card-body">
            <div class="row">
              <div class="col-12 col-md-4 col-lg-3">
                <iframe width="100%" height="200"
                src="<%= video.yt_url %>">
                </iframe>
              </div>
              <div class="col-12 col-md-8 col-lg-9">
                <h3><%= link_to video.title, 'javascript:void(0)' %></h3>
                <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution.</p>            
                <% if user_signed_in? && @user_fav_video_ids.include?(video.id) %>
                  <%= link_to 'Remov from favourite', remove_from_favourite_video_path(video), method: :post, class: 'btn btn-danger btn-lg mt-3' %>
                <% else %>  
                  <%= link_to 'Add to favourite', add_to_favourite_video_path(video), method: :post, class: 'btn btn-primary btn-lg mt-3' %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @video.title %>
</p>

<p>
  <strong>Yt url:</strong>
  <%= @video.yt_url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @video.description %>
</p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %> |

app/views/videos/show_all_fav_videos.html.erb
<div class="container">
  <h2>Favourite Video List</h2>
  <% if current_user.id && current_user.user_favourite_videos.present? %>
    <div class="row">
      <div class="col-12 col-md-11 mx-md-auto col-lg-9 mx-lg-auto">
        <% @videos.each do |video| %>
          <% if @user_fav_videos.include?(video.id) %>
            <div class="card shadow rounded-0 mt-3">
              <div class="card-body">
                <div class="row">
                  <div class="col-12 col-md-4 col-lg-3">
                    <iframe width="100%" height="200"
                    src="<%= video.yt_url %>">
                    </iframe>
                  </div>
                  <div class="col-12 col-md-8 col-lg-9">
                    <h3><%= link_to video.title, 'javascript:void(0)' %></h3>
                    <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution.</p>            
                  <%= link_to "Back", videos_path, class: 'btn btn-light btn-lg mt-4' %>
                  </div>
                </div>
              </div>
            </div>          
          <% end %>
        <% end %>
      </div>
    </div>
  <% else %>
  <h2>No data available please Add video as favourite.</h2>
  <%= link_to "Back", videos_path, class: 'btn btn-light btn-lg mt-4' %>
  <% end %>
  </div>