config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  root "books#index"
  resources :articles
  resources :books

  get 'video-gallary' => "books#yt_videos"
  get  'fav_videos', to: 'videos#show_all_fav_videos'
  
  resources :videos do 
    member do 
      post :add_to_favourite
      post :remove_from_favourite
    end
  end
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :users
end

app/controllers/books_controller.rb
require 'net/http'
class BooksController < ApplicationController

  include CommonCrud

  def yt_videos
    response = RestClient.get('http://localhost:3001/videos')
    
    puts response
    @youtube_videos = JSON.parse(response.body)

    # uri = URI('http://localhost:3001/videos')
    # response = Net::HTTP.get(uri)

    # puts response 
    # @videos = JSON.parse(response)
  end

  def display_video
    uri = URI("http://localhost:3001/videos/#{params[:video_id]}")
    response = Net::HTTP.get(uri)
    puts response 
    @youtube_vides = JSON.parse(response)
  end

  private

    def book_params
      params.require(:book).permit!
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :isbn %>
    <%= form.text_field :isbn %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Price</th>
      <th>Isbn</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.description %></td>
        <td><%= book.image_url %></td>
        <td><%= book.price %></td>
        <td><%= book.isbn %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %></br>
<%= link_to 'Log Out', destroy_user_session_path, method: :delete %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @book.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @book.isbn %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/books/yt_videos.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-11 mx-md-auto col-lg-9 mx-lg-auto">
      <% @videos.each do |video| %>
        <div class="card shadow rounded-0 mt-3">
          <div class="card-body">
            <div class="row">
              <div class="col-12 col-md-4 col-lg-3">
                <iframe width="100%" height="200"
                src="<%= video["yt_url"] %>">
                </iframe>
              </div>
              <div class="col-12 col-md-8 col-lg-9">
                <h6><%= link_to video["id"] %></h6>
                <h3><%= link_to video["title"], 'javascript:void(0)' %></h3>
                <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution.</p>
                <%= link_to 'Add to favourite', add_favourite_videos_path(video), class: 'btn btn-primary btn-lg mt-3', id: 'yt_videos' %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    </div>
  </div>
</div>